# Generated by Django 3.1 on 2022-05-29 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=220, null=True, verbose_name='Nombre')),
                ('cod_departamento', models.SmallIntegerField(blank=True, null=True, verbose_name='Departamento')),
                ('delivery', models.BooleanField(default=False, verbose_name='Disponible/No Disponible')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=220, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=220, null=True, verbose_name='Nombre')),
                ('servidor_propio', models.BooleanField(default=True, verbose_name='Servidor Propio')),
                ('cod_servicio', models.CharField(blank=True, max_length=220, null=True, verbose_name='Código de Servicio')),
                ('usuario', models.CharField(blank=True, max_length=220, null=True, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=220, null=True, verbose_name='Contraseña')),
                ('servidor_pagopar', models.BooleanField(default=True, verbose_name='Servidor PagoPar')),
                ('token_publico', models.CharField(blank=True, max_length=220, null=True, verbose_name='token publico')),
                ('token_privado', models.CharField(blank=True, max_length=220, null=True, verbose_name='token privado')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=220, null=True, verbose_name='Apellidos')),
                ('type', models.CharField(choices=[('VE', 'Vendedor'), ('TR', 'Transportador'), ('AD', 'Administrador')], default='AD', max_length=2, verbose_name='Tipo')),
                ('active', models.BooleanField(default=True, verbose_name='Activado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-last_name'],
            },
        ),
    ]
