# Generated by Django 3.1 on 2021-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-last_name'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ref_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('VE', 'Vendedor'), ('TR', 'Transportador'), ('AD', 'Administrador')], default='AD', max_length=2, verbose_name='Estado'),
        ),
    ]
