# Generated by Django 3.1 on 2021-12-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.empresa'),
        ),
    ]
