# Generated by Django 3.1 on 2021-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211212_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cod_servicio',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Código de Servicio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='password',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_privado',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='token privado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_publico',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='token publico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Usuario'),
        ),
    ]
