# Generated by Django 3.1 on 2021-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20211215_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='servidor_pagopar',
            field=models.BooleanField(default=True, verbose_name='Servidor PagoPar'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='servidor_propio',
            field=models.BooleanField(default=True, verbose_name='Servidor Propio'),
        ),
    ]
