# Generated by Django 3.1 on 2020-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date_created'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='concept',
            field=models.CharField(default='Pago de Producto', max_length=20, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pendiente', max_length=200, verbose_name='Estado'),
        ),
    ]
