# Generated by Django 3.1 on 2020-11-10 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201108_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Vencimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
    ]
