# Generated by Django 3.1 on 2021-12-10 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211210_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 1, 59, 50, 494773), verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PP', 'Pago Pendiente'), ('PC', 'Pago Completado'), ('PR', 'Pago Revertido'), ('CA', 'Cancelado'), ('RE', 'Recibido'), ('EM', 'Empaquetado'), ('EC', 'En Camino'), ('LR', 'Listo Para Retiro'), ('PL', 'Problemas Logísticos'), ('RE', 'Retirado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
