# Generated by Django 3.1 on 2020-11-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201110_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='transaction_anulate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Transacción de Anulación'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='transaction',
            field=models.IntegerField(verbose_name='Nº Transacción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 15, 33, 3, 546788), verbose_name='Fecha Vencimiento'),
        ),
    ]
