# Generated by Django 3.1 on 2021-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(max_length=20, verbose_name='Concepto'),
        ),
    ]
