# Generated by Django 3.1 on 2020-11-10 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201110_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 17, 35, 57, 342927), verbose_name='Fecha Vencimiento'),
        ),
    ]
