# Generated by Django 3.1 on 2020-11-10 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201110_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='transaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Transacción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 17, 36, 36, 613041), verbose_name='Fecha Vencimiento'),
        ),
    ]
