# Generated by Django 3.1 on 2021-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211210_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(max_length=255, verbose_name='Concepto'),
        ),
    ]
