# Generated by Django 3.1 on 2021-12-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_empresa'),
        ('core', '0007_auto_20211210_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa'),
        ),
        migrations.AddField(
            model_name='fee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa'),
        ),
    ]
