# Generated by Django 3.1 on 2020-11-13 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201110_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 18, 4, 8, 933964), verbose_name='Fecha Vencimiento'),
        ),
    ]
