# Generated by Django 3.1 on 2021-12-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default='14-12-2021', verbose_name='Fecha Vencimiento'),
        ),
    ]
