# Generated by Django 3.1 on 2021-12-11 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211211_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='transaction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº Transacción'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='transaction_anulate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº Transacción de Anulación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 3, 55, 0, 509254, tzinfo=utc), verbose_name='Fecha Vencimiento'),
        ),
    ]
