# Generated by Django 3.1 on 2021-04-06 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210406_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 18, 33, 59, 303139), verbose_name='Fecha Vencimiento'),
        ),
    ]
