# Generated by Django 3.1 on 2021-04-06 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210406_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 18, 48, 41, 966563), verbose_name='Fecha Vencimiento'),
        ),
    ]
