# Generated by Django 3.1 on 2021-04-07 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210406_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 20, 9, 29, 594388), verbose_name='Fecha Vencimiento'),
        ),
    ]
