# Generated by Django 3.1 on 2021-04-14 00:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210406_1848'),
        ('core', '0013_auto_20210406_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plataform',
            field=models.CharField(choices=[('ap', 'Aqui Pago'), ('pe', 'Pago Express')], default='ap', max_length=2, verbose_name='Método de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 25, 42, 51971), verbose_name='Fecha Vencimiento'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_payable', models.IntegerField(blank=True, null=True, verbose_name='Monto Mensual a Pagar')),
                ('amount_fees', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Meses')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
