# Generated by Django 3.1 on 2021-12-12 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211211_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 3, 22, 50, 631137, tzinfo=utc), verbose_name='Fecha Vencimiento'),
        ),
    ]
