# Generated by Django 3.1 on 2021-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211212_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PP', 'Pago Pendiente'), ('PC', 'Pago Completado'), ('PA', 'Pago Anulado'), ('CA', 'Cancelado'), ('RE', 'Recibido'), ('EM', 'Empaquetado'), ('EC', 'En Camino'), ('LR', 'Listo Para Retiro'), ('PL', 'Problemas Logísticos'), ('RE', 'Retirado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
