# Generated by Django 3.1 on 2021-04-14 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210413_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['id'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AddField(
            model_name='fee',
            name='months_paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Meses Pagados'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount_fees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses a Pagar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 47, 33, 679009), verbose_name='Fecha Vencimiento'),
        ),
    ]
