# Generated by Django 3.1 on 2021-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211212_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='commission',
            field=models.IntegerField(default=3, verbose_name='Comisión'),
        ),
    ]
