# Generated by Django 3.1 on 2021-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_checkout_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo de Referencia'),
        ),
    ]
