# Generated by Django 3.1 on 2021-04-14 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210414_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='transaction_reversed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Transacción de Revertido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 19, 44, 20, 455693), verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pe', 'Pendiente'), ('pa', 'Pagado'), ('an', 'Anulado'), ('re', 'Reversado')], default='pe', max_length=2, verbose_name='Estado'),
        ),
    ]
