# Generated by Django 3.1 on 2021-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='Servidor Propio', max_length=255, verbose_name='Origen'),
        ),
    ]
