# Generated by Django 3.1 on 2021-04-14 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210414_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 19, 44, 29, 683922), verbose_name='Fecha Vencimiento'),
        ),
    ]
