# Generated by Django 3.1 on 2021-12-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_payment_hash_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='owner',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
    ]
