# Generated by Django 3.1 on 2021-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20211214_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origen'),
        ),
    ]
