# Generated by Django 3.1 on 2021-12-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_checkout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PP', 'Pago Pendiente'), ('PC', 'Pago Completado'), ('PA', 'Pago Anulado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
