# Generated by Django 3.1 on 2021-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211215_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PP', 'Pago Pendiente'), ('PC', 'Pago Completado'), ('PA', 'Pago Anulado'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
