# Generated by Django 3.1 on 2021-04-17 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210416_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 21, 23, 27, 426083), verbose_name='Fecha Vencimiento'),
        ),
    ]
