# Generated by Django 3.1 on 2021-04-17 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210416_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 21, 25, 49, 416424), verbose_name='Fecha Vencimiento'),
        ),
    ]
