# Generated by Django 3.1 on 2021-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagopar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='commission',
            field=models.IntegerField(default=6, verbose_name='Comisión'),
        ),
    ]
