# Generated by Django 3.1 on 2022-05-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('type_document', models.CharField(choices=[('CI', 'Cedula de Identidad'), ('RU', 'Registro Unico del Contribuyente'), ('PA', 'Pasaporte'), ('OT', 'Otros')], default='CI', max_length=2, verbose_name='Estado')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellidos')),
                ('business_name', models.CharField(blank=True, max_length=220, null=True, verbose_name='Razón Social')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Principal')),
                ('phone2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Secundario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.BooleanField(default=True, verbose_name='Visible')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.ciudad')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.departamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['document'],
            },
        ),
    ]
