# Generated by Django 3.1 on 2021-12-10 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.IntegerField(verbose_name='Documento')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellidos')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Principal')),
                ('phone2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Secundario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.ciudad')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.departamento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['document'],
            },
        ),
    ]
