# Generated by Django 3.1 on 2021-04-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.IntegerField(verbose_name='Documento')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellidos')),
                ('region', models.CharField(choices=[('PY01', 'Concepcion'), ('PY02', 'San Pedro'), ('PY03', 'Cordillera'), ('PY04', 'Guaira'), ('PY05', 'Caaguazu'), ('PY06', 'Caazapa'), ('PY07', 'Itapua'), ('PY08', 'Misiones'), ('PY09', 'Paraguari'), ('PY10', 'Alto Parana'), ('PY11', 'Central'), ('PY12', 'Neembucu'), ('PY13', 'Amambay'), ('PY14', 'Canindeyu'), ('PY15', 'Presidente Hayes'), ('PY16', 'Boqueron'), ('PY17', 'Alto Paraguay')], max_length=4, verbose_name='Departamento')),
                ('city', models.CharField(max_length=220, verbose_name='Ciudad')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['document'],
            },
        ),
    ]
