# Generated by Django 3.1 on 2021-04-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Principal'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Secundario'),
        ),
    ]
