# Generated by Django 3.1 on 2021-12-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
    ]
