# Generated by Django 3.1 on 2021-12-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211212_0022'),
        ('clients', '0005_remove_client_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa'),
        ),
    ]
