# Generated by Django 3.1 on 2021-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20211213_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.AddField(
            model_name='client',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
