# Generated by Django 3.1 on 2021-12-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20211213_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_document',
            field=models.CharField(choices=[('CI', 'Cedula de Identidad'), ('RUC', 'Registro Unico del Contribuyente')], default='CI', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres'),
        ),
    ]
