# Generated by Django 3.1 on 2021-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20211215_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_document',
            field=models.CharField(choices=[('CI', 'Cedula de Identidad'), ('RU', 'Registro Unico del Contribuyente'), ('PA', 'Pasaporte'), ('OT', 'Otros')], default='CI', max_length=2, verbose_name='Estado'),
        ),
    ]
